version: "3"

networks:
  project_net:
    external:
      name: project_net

services:
  soap-server:
    image: soap-server-image
    container_name: soap-server
    # Configuration for building the docker image for the backend service
    build:
      context: ./ # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - project_net
    ports:
      - 8082:8082