
package com.example.springdemo.soapservice.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DoctorSoapService", targetNamespace = "http://services.soapService.springdemo.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DoctorSoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.ActivitiesListDTO
     */
    @WebMethod(action = "getActivities")
    @WebResult(partName = "return")
    @Action(input = "getActivities", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getPatientActivitiesResponse")
    public ActivitiesListDTO getPatientActivities(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.ActivitiesListDTO
     */
    @WebMethod(action = "getActivityStatus")
    @WebResult(partName = "return")
    @Action(input = "getActivityStatus", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getActivityOnDateResponse")
    public ActivitiesListDTO getActivityOnDate(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "newRecommendation")
    @WebResult(partName = "return")
    @Action(input = "newRecommendation", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/newRecommendationResponse")
    public String newRecommendation(
        @WebParam(name = "arg0", partName = "arg0")
        RecommendationDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.PatientDTO
     */
    @WebMethod(action = "getDetails")
    @WebResult(partName = "return")
    @Action(input = "getDetails", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getPatientDetailsResponse")
    public PatientDTO getPatientDetails(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.RecommendationListDTO
     */
    @WebMethod(action = "getRecommendation")
    @WebResult(partName = "return")
    @Action(input = "getRecommendation", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getRecommendationsResponse")
    public RecommendationListDTO getRecommendations(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.example.springdemo.soapservice.services.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.soapService.springdemo.example.com/DoctorSoapService/getAllPatientsRequest", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getAllPatientsResponse")
    public ArrayList getAllPatients();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.DoctorDTO
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.soapService.springdemo.example.com/DoctorSoapService/getDoctorRequest", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getDoctorResponse")
    public DoctorDTO getDoctor(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.MonitoredPillsList
     */
    @WebMethod(action = "getPills")
    @WebResult(partName = "return")
    @Action(input = "getPills", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/getNotTakenPillsResponse")
    public MonitoredPillsList getNotTakenPills(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.example.springdemo.soapservice.services.DoctorDTO
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.soapService.springdemo.example.com/DoctorSoapService/loginRequest", output = "http://services.soapService.springdemo.example.com/DoctorSoapService/loginResponse")
    public DoctorDTO login(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
